spring:
  application:
    name: JobPostService
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:JobPostDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080